IDIOMA_ACTUAL = "es"


TEXTOS = {
    "es": {
        "app_title": "AI BUSINESS ASSISTANT",
        "executive_overview": "RESUMEN EJECUTIVO",
        "business_overview": "Resumen financiero y operativo de tu negocio",

        "dashboard": "Dashboard",
        "clientes": "Clientes",
        "ventas": "Ventas",
        "inventario": "Inventario",
        "gastos": "Gastos",
        "cuentas_por_cobrar": "Cuentas por cobrar",
        "resumen_negocio": "Resumen del negocio",
        "diagnostico": "Diagnóstico inteligente",
        "salir": "Salir",

        "idioma": "Idioma",
        "espanol": "Español",
        "ingles": "English",

        "client_management": "GESTIÓN DE CLIENTES",
        "client_directory_subtitle": "Directorio y seguimiento de clientes",
        "new_client": "+ Nuevo cliente",
        "client_intelligence": "Resumen por cliente",
        "total_clients": "TOTAL DE CLIENTES",
        "client_directory": "DIRECTORIO DE CLIENTES",
        "close": "Cerrar",

        "new_client_title": "NUEVO CLIENTE",
        "new_client_subtitle": "Crear un nuevo perfil de cliente",
        "client_information": "INFORMACIÓN DEL CLIENTE",
        "client_name": "Nombre del cliente",
        "save_client": "Guardar cliente",
        "cancel": "Cancelar",

        "sales_management": "GESTIÓN DE VENTAS",
        "sales_subtitle": "Control de ingresos, transacciones y ganancias",
        "new_sale": "+ Nueva venta",
        "sales_history": "Historial de ventas",
        "profit_analytics": "Análisis de ganancias",
        "total_sales": "VENTAS TOTALES",
        "known_profit": "GANANCIA CONOCIDA",
        "transactions": "TRANSACCIONES",
        "search_sales": "BUSCAR CLIENTE, CÓDIGO, PRODUCTO O FECHA",
        "sales_found": "VENTAS ENCONTRADAS",
        "total_sold": "TOTAL VENDIDO",
        "known_revenue": "INGRESOS CONOCIDOS",
        "known_costs": "COSTOS CONOCIDOS",

        "select_client": "SELECCIONAR CLIENTE",
        "total_purchased": "TOTAL COMPRADO",
        "credit_sales": "VENTAS A CRÉDITO",
        "balance_due": "SALDO PENDIENTE",
        "client_summary": "RESUMEN DEL CLIENTE",
        "detailed_sales_history": "HISTORIAL DETALLADO DE VENTAS",

        "inventory_management": "GESTIÓN DE INVENTARIO",
        "inventory_subtitle": "Control de productos, existencias y reposiciones",
        "new_product": "+ Nuevo producto",
        "new_restock": "+ Nueva reposición",
        "edit_product": "Editar producto",
        "restock_history": "Historial de reposiciones",
        "purchase_list": "Lista de compra",
        "inventory_search": "BUSCAR POR CÓDIGO O NOMBRE",
        "products_found": "PRODUCTOS ENCONTRADOS",
        "inventory_capital": "CAPITAL EN INVENTARIO",
        "inventory_value": "VALOR DEL INVENTARIO",
        "potential_profit": "GANANCIA POTENCIAL",
        "stock_available": "Stock disponible",
        "average_cost": "Costo promedio",
        "sale_price": "Precio de venta",
        "potential_value": "Valor potencial",

        "register_product": "REGISTRAR PRODUCTO",
        "product_code": "Código del producto",
        "product_name": "Nombre del producto",
        "initial_quantity": "Cantidad inicial",
        "unit_cost": "Costo unitario",
        "save_product": "Guardar producto",

        "register_restock": "REGISTRAR REPOSICIÓN",
        "quantity": "Cantidad",
        "supplier_cost": "Costo del proveedor",
        "save_restock": "Guardar reposición",

        "select_product": "SELECCIONAR PRODUCTO",
        "continue_edit": "Continuar a editar",
        "restock_history_title": "HISTORIAL DE REPOSICIONES",
        "total_restock_investment": "INVERSIÓN TOTAL EN REPOSICIONES",
        "purchase_list_title": "LISTA DE COMPRA SUGERIDA",
        "purchase_list_subtitle": "Productos con 10 unidades o menos",
        "current_stock": "Stock actual",
        "buy_units": "Comprar",
        "estimated_unit_cost": "Costo estimado unitario",
        "estimated_investment": "Inversión estimada",
        "estimated_total_investment": "INVERSIÓN TOTAL ESTIMADA",
        "copy_list": "Copiar lista",
        "code": "Código",
        "product": "Producto",
        "date": "Fecha",
        "units_purchased": "Unidades compradas",
        "supplier_cost_label": "Costo proveedor",
        "investment": "Inversión",


        "expense_management": "GESTIÓN DE GASTOS",
        "expense_subtitle": "Control de costos y gastos operativos",
        "new_expense": "+ Nuevo gasto",
        "total_expenses": "GASTOS TOTALES",
        "expense_count": "REGISTROS",
        "description": "Descripción",
        "category": "Categoría",
        "amount": "Monto",
        "register_expense": "REGISTRAR GASTO",
        "save_expense": "Guardar gasto",

        "receivables_management": "CUENTAS POR COBRAR",
        "receivables_subtitle": "Control de crédito, vencimientos y pagos",
        "pending": "Pendientes",
        "paid": "Pagadas",
        "total_pending": "TOTAL PENDIENTE",
        "total_overdue": "TOTAL VENCIDO",
        "due_soon": "VENCE PRONTO",
        "clients_with_debt": "CLIENTES CON DEUDA",
        "sale_date": "Fecha de venta",
        "due_date": "Vencimiento",
        "paid_amount": "Pagado",
        "status": "Estado",
        "alert": "Alerta",
        "payment_history": "Historial de pagos",
        "no_payments": "Sin pagos registrados",
        "register_payment": "Registrar pago",

        "business_summary_title": "RESUMEN DEL NEGOCIO",
        "business_summary_subtitle": "Visión ejecutiva del rendimiento general",
        "registered_clients": "CLIENTES REGISTRADOS",
        "registered_sales": "VENTAS REGISTRADAS",
        "sales_revenue": "INGRESOS POR VENTAS",
        "operating_expenses": "GASTOS OPERATIVOS",
        "cash_flow": "FLUJO DE CAJA",
        "financial_status": "ESTADO FINANCIERO",
        "inventory_position": "POSICIÓN DE INVENTARIO",

        "diagnosis_title": "DIAGNÓSTICO INTELIGENTE",
        "diagnosis_subtitle": "Análisis automático del negocio",
        "financial_state": "ESTADO FINANCIERO",
        "analysis": "ANÁLISIS",
        "recommendation": "RECOMENDACIÓN",
        "expense_ratio": "Gastos sobre ventas",
        "positive": "POSITIVO",
        "negative": "NEGATIVO",
        "balanced": "EQUILIBRADO",
        "refresh": "Actualizar",
        "open_dashboard": "Abrir Dashboard Ejecutivo",
    },

    "en": {
        "app_title": "AI BUSINESS ASSISTANT",
        "executive_overview": "EXECUTIVE OVERVIEW",
        "business_overview": "Financial and operational overview of your business",

        "dashboard": "Dashboard",
        "clientes": "Clients",
        "ventas": "Sales",
        "inventario": "Inventory",
        "gastos": "Expenses",
        "cuentas_por_cobrar": "Accounts Receivable",
        "resumen_negocio": "Business Summary",
        "diagnostico": "Intelligent Diagnosis",
        "salir": "Exit",

        "idioma": "Language",
        "espanol": "Español",
        "ingles": "English",

        "client_management": "CLIENT MANAGEMENT",
        "client_directory_subtitle": "Customer directory and relationship overview",
        "new_client": "+ New client",
        "client_intelligence": "Client intelligence",
        "total_clients": "TOTAL CLIENTS",
        "client_directory": "CLIENT DIRECTORY",
        "close": "Close",

        "new_client_title": "NEW CLIENT",
        "new_client_subtitle": "Create a new customer profile",
        "client_information": "CLIENT INFORMATION",
        "client_name": "Client name",
        "save_client": "Save client",
        "cancel": "Cancel",

        "sales_management": "SALES MANAGEMENT",
        "sales_subtitle": "Revenue, transactions and profit control",
        "new_sale": "+ New sale",
        "sales_history": "Sales history",
        "profit_analytics": "Profit analytics",
        "total_sales": "TOTAL SALES",
        "known_profit": "KNOWN PROFIT",
        "transactions": "TRANSACTIONS",
        "search_sales": "SEARCH CLIENT, CODE, PRODUCT OR DATE",
        "sales_found": "SALES FOUND",
        "total_sold": "TOTAL SOLD",
        "known_revenue": "KNOWN REVENUE",
        "known_costs": "KNOWN COSTS",

        "select_client": "SELECT CLIENT",
        "total_purchased": "TOTAL PURCHASED",
        "credit_sales": "CREDIT SALES",
        "balance_due": "BALANCE DUE",
        "client_summary": "CLIENT SUMMARY",
        "detailed_sales_history": "DETAILED SALES HISTORY",

        "inventory_management": "INVENTORY MANAGEMENT",
        "inventory_subtitle": "Product, stock and replenishment control",
        "new_product": "+ New product",
        "new_restock": "+ New restock",
        "edit_product": "Edit product",
        "restock_history": "Restock history",
        "purchase_list": "Purchase list",
        "inventory_search": "SEARCH BY CODE OR NAME",
        "products_found": "PRODUCTS FOUND",
        "inventory_capital": "INVENTORY CAPITAL",
        "inventory_value": "INVENTORY VALUE",
        "potential_profit": "POTENTIAL PROFIT",
        "stock_available": "Stock available",
        "average_cost": "Average cost",
        "sale_price": "Sale price",
        "potential_value": "Potential value",

        "register_product": "REGISTER PRODUCT",
        "product_code": "Product code",
        "product_name": "Product name",
        "initial_quantity": "Initial quantity",
        "unit_cost": "Unit cost",
        "save_product": "Save product",

        "register_restock": "REGISTER RESTOCK",
        "quantity": "Quantity",
        "supplier_cost": "Supplier cost",
        "save_restock": "Save restock",

        "select_product": "SELECT PRODUCT",
        "continue_edit": "Continue to edit",
        "restock_history_title": "RESTOCK HISTORY",
        "total_restock_investment": "TOTAL RESTOCK INVESTMENT",
        "purchase_list_title": "SUGGESTED PURCHASE LIST",
        "purchase_list_subtitle": "Products with 10 units or less",
        "current_stock": "Current stock",
        "buy_units": "Buy",
        "estimated_unit_cost": "Estimated unit cost",
        "estimated_investment": "Estimated investment",
        "estimated_total_investment": "TOTAL ESTIMATED INVESTMENT",
        "copy_list": "Copy list",
        "code": "Code",
        "product": "Product",
        "date": "Date",
        "units_purchased": "Units purchased",
        "supplier_cost_label": "Supplier cost",
        "investment": "Investment",


        "expense_management": "EXPENSE MANAGEMENT",
        "expense_subtitle": "Operating cost and expense control",
        "new_expense": "+ New expense",
        "total_expenses": "TOTAL EXPENSES",
        "expense_count": "RECORDS",
        "description": "Description",
        "category": "Category",
        "amount": "Amount",
        "register_expense": "REGISTER EXPENSE",
        "save_expense": "Save expense",

        "receivables_management": "ACCOUNTS RECEIVABLE",
        "receivables_subtitle": "Credit, due-date and payment control",
        "pending": "Pending",
        "paid": "Paid",
        "total_pending": "TOTAL PENDING",
        "total_overdue": "TOTAL OVERDUE",
        "due_soon": "DUE SOON",
        "clients_with_debt": "CLIENTS WITH DEBT",
        "sale_date": "Sale date",
        "due_date": "Due date",
        "paid_amount": "Paid",
        "status": "Status",
        "alert": "Alert",
        "payment_history": "Payment history",
        "no_payments": "No payments registered",
        "register_payment": "Register payment",

        "business_summary_title": "BUSINESS SUMMARY",
        "business_summary_subtitle": "Executive overview of overall performance",
        "registered_clients": "REGISTERED CLIENTS",
        "registered_sales": "REGISTERED SALES",
        "sales_revenue": "SALES REVENUE",
        "operating_expenses": "OPERATING EXPENSES",
        "cash_flow": "CASH FLOW",
        "financial_status": "FINANCIAL STATUS",
        "inventory_position": "INVENTORY POSITION",

        "diagnosis_title": "INTELLIGENT DIAGNOSIS",
        "diagnosis_subtitle": "Automatic business analysis",
        "financial_state": "FINANCIAL STATE",
        "analysis": "ANALYSIS",
        "recommendation": "RECOMMENDATION",
        "expense_ratio": "Expenses over sales",
        "positive": "POSITIVE",
        "negative": "NEGATIVE",
        "balanced": "BALANCED",
        "refresh": "Refresh",
        "open_dashboard": "Open Executive Dashboard",
    }
}


def cambiar_idioma(codigo):
    global IDIOMA_ACTUAL

    if codigo in TEXTOS:
        IDIOMA_ACTUAL = codigo


def obtener_idioma():
    return IDIOMA_ACTUAL


def t(clave):
    idioma = TEXTOS.get(
        IDIOMA_ACTUAL,
        TEXTOS["es"]
    )

    return idioma.get(
        clave,
        clave
    )
